#!/usr/bin/env bash
# demo/record.sh — record an asciinema cast of REAL claude-j.
#
# Usage:  bash demo/record.sh
# Run from a plain terminal (NOT inside zellij). asciinema wraps
# zellij, you start claude-j inside, drive a real demo, exit.
#
# What you see at the end:
#   demo/claude-j.cast   — asciinema recording (replay or upload)
#   demo/demo.gif        — generated by `agg` (run separately)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CAST="$ROOT/demo/claude-j.cast"

if [ -n "${ZELLIJ:-}" ]; then
  echo "demo/record.sh: don't run this from inside an existing zellij session." >&2
  echo "                open a plain terminal, then re-run." >&2
  exit 1
fi

for cmd in claude-j asciinema zellij; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "missing: $cmd" >&2; exit 1; }
done

cat <<'TIPS'
============================================================
Recording starts in 3 seconds. Inside the zellij session:
  1. Type:    claude-j                        (then Enter)
  2. Wait for the claude prompt.
  3. Give it a prompt that spawns 2-3 subagents in parallel,
     e.g.:
        开三个 Explore agent 并行：扫一下 ~/Documents、
        ~/Projects、~/ai 下面最近一周改过的文件
  4. Watch the right column auto-populate. Let them run for
     30-60s so the recording captures the equal-height layout
     and live tool calls.
  5. /exit in the claude-main pane.
  6. Then Ctrl+Q (or Ctrl+G then q) to quit zellij.
Recording stops automatically when zellij exits.
============================================================
TIPS
sleep 3

asciinema rec "$CAST" --overwrite \
  --title "claude-j" \
  --window-size 200x55 \
  --command zellij

echo
echo "saved: $CAST"
echo
echo "next:"
echo "  agg $CAST demo/demo.gif       # render GIF for README embed"
echo "  asciinema upload $CAST        # publish, get a URL"
